# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envref < Formula
  desc "CLI tool for separating config from secrets in .env files"
  homepage "https://github.com/xcke/envref"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xcke/envref/releases/download/v0.4.0/envref_0.4.0_darwin_amd64.tar.gz"
      sha256 "69276259264043ff08d2493b06de34917b2eac9b9d491cb58594dae7c3c10dbd"

      define_method(:install) do
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xcke/envref/releases/download/v0.4.0/envref_0.4.0_darwin_arm64.tar.gz"
      sha256 "72d636b20bb2c1289d787da8082c1a7598eb34af80f26d730d1aa8737b6d955c"

      define_method(:install) do
        bin.install "envref"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.4.0/envref_0.4.0_linux_amd64.tar.gz"
      sha256 "bc1dfba92a7fbcb433aceffa24fbd2e981463635554266de03ee235bf336dfe6"
      define_method(:install) do
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.4.0/envref_0.4.0_linux_arm64.tar.gz"
      sha256 "9ffd7d85d2db3b141699be9a094e77af36fd39282a39506aafada65c4545e3cf"
      define_method(:install) do
        bin.install "envref"
      end
    end
  end

  test do
    assert_match "envref", shell_output("#{bin}/envref --help")
  end
end
