# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envref < Formula
  desc "CLI tool for separating config from secrets in .env files"
  homepage "https://github.com/xcke/envref"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xcke/envref/releases/download/v0.3.0/envref_0.3.0_darwin_amd64.tar.gz"
      sha256 "1805edd69918883a73079714919c5097d296c51c96ab6b9e6bfe7069774d97bc"

      define_method(:install) do
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xcke/envref/releases/download/v0.3.0/envref_0.3.0_darwin_arm64.tar.gz"
      sha256 "f03144de3df55598e6ae8fddec4ea9217a03763b747684e8ad209a5ee1a48d8a"

      define_method(:install) do
        bin.install "envref"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.3.0/envref_0.3.0_linux_amd64.tar.gz"
      sha256 "5d973ff445af67a8998edca820e7bdc3753ca904549dc0529455eb7adb207d37"
      define_method(:install) do
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.3.0/envref_0.3.0_linux_arm64.tar.gz"
      sha256 "41d563072c943da790d67560c75ee1567691ebfa107840fb26eb0e3c20f8d2fa"
      define_method(:install) do
        bin.install "envref"
      end
    end
  end

  test do
    assert_match "envref", shell_output("#{bin}/envref --help")
  end
end
