# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envref < Formula
  desc "CLI tool for separating config from secrets in .env files"
  homepage "https://github.com/xcke/envref"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xcke/envref/releases/download/v0.1.0/envref_0.1.0_darwin_amd64.tar.gz"
      sha256 "af1ac39bd913e4721eb03f364af0b52c757177967d48d9dce4b9166b15f987d7"

      def install
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xcke/envref/releases/download/v0.1.0/envref_0.1.0_darwin_arm64.tar.gz"
      sha256 "55190ebd47585f11ca5b56f9755f2ff6576edc8f57181ee20d355703a4a88b8d"

      def install
        bin.install "envref"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.1.0/envref_0.1.0_linux_amd64.tar.gz"
      sha256 "f04a90ab646db07801cf4ab579cc6de05bc4cae8fd833dffa879b21a67d83373"
      def install
        bin.install "envref"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xcke/envref/releases/download/v0.1.0/envref_0.1.0_linux_arm64.tar.gz"
      sha256 "98c196ac357c8efe2750cba25886edc9df56370a4810c283cfb2b2a5fc0ba94d"
      def install
        bin.install "envref"
      end
    end
  end

  test do
    assert_match "envref", shell_output("#{bin}/envref --help")
  end
end
